# Generated by Django 2.2.1 on 2019-05-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
