# Generated by Django 2.2.1 on 2019-05-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190512_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
